config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[index show new create] do
    resources :items, only: %i[new create]
  end
  devise_for :users
  root to: "splash#index"

  get "categories" , to: "categories#index", as: :custom_categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :category
  belongs_to :item
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categorizations
  has_many :items, through: :categorizations

  mount_uploader :icon, IconUploader
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_many :categorizations
  has_many :categories, through: :categorizations

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories
  has_many :transactions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(_resource)
    categories_path
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id).includes([:items]).order('created_at DESC')
  end

  # GET /categories/1 or /categories/1.json
  def show
    if current_user.id.to_i == Category.find(params[:id]).user_id.to_i
      @category = Category.find(params[:id])
    else
      redirect_to categories_path
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)
    respond_to do |_format|
      if @category.save
        redirect_to custom_categories_path, notice: 'Category was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items/new
  def new
    if current_user.id.to_i == Category.find(params[:category_id]).user_id.to_i
      @item = Item.new
      @categories = Category.where(user_id: current_user.id)
    else
      redirect_to categories_path
    end
  end

  # POST /items or /items.json
  def create
    @item = Item.new(name: params[:item][:name], amount: params[:item][:amount], user_id: current_user.id)
    if params[:item][:selected_ids]
      if save_item_and_categorization
        redirect_to categories_path(params[:category_id])
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to Categorizations_path(params[:category_id]), alert: 'please select at least one checkbox.'
    end
  end

  private

  def save_item_and_categorization
    ActiveRecord::Base.transaction do
      @item.save
      params[:item][:selected_ids].each do |id|
        Categorization.create(item_id: @item.id, category_id: id.to_i)
      end
    end
  rescue ActiveRecord::RecordInvalid
    false
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :amount, selected_id: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<div id="categories" class="contain">
<div class="back-lin">
<%= link_to :back do %>
  <%= image_tag('icons8-left-24 (1).png') %>
<% end %>
<h2>CATEGORIES</h2>
<div class="acti">
<%= button_to "OUT", destroy_user_session_path, method: :delete, class: "btnn" %>
</div>
</div>
  <% @categories.each do |category| %>
    <%= link_to "/categories/#{category.id}" do %>
  <div id="<%= dom_id category %>" class="categories-container">
    <div class="icon">
    <%= image_tag category.icon.url %>
    <div class="nams">
    <p class="namz"><%= category.name.capitalize %></p>
    <br>
    <p class="dat"><%= category.created_at.strftime('%d-%b-%Y') %></p>
  </div>
    </div>

  <p>
  $<%= category.items.map { |item| item.amount }.sum %>
  </p>
  </div>
<% end %>

  <% end %>
  <div class="new-cs">
  <p class="new-s"><%= link_to "New category", new_category_path %></p>
  </div>
</div>

app/views/categories/new.html.erb
<div class="contain">
<%= form_with(model: @category) do |form| %>
    <div class="back-lin">
  <%= link_to categories_path do %>
    <%= image_tag('icons8-left-24 (1).png') %>
  <% end %>
  <h2>NEW CATEGORY</h2>
  <div class="acti">
  <%= form.submit "Save", class: "btnn" %>
  </div>
  </div>
  <% if @category.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
      <% @category.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

    <div class="field">
      <%= form.text_field :name, placeholder: "Name", autofocus: true %>
    </div>
  
    <div>
      <%= form.label :icon, style: "display: block" %>
      <%= form.file_field :icon %>
    </div>
  <% end %>
  
</div>

app/views/categories/show.html.erb
<div id="categories" class="contains">
<div class="back-lins">
<%= link_to categories_path do %>
  <%= image_tag('icons8-left-24 (1).png') %>
<% end %>
<div class="acent">
<h2>TRANSACTIONS</h2>
<p>Most Ancient</p>
</div>
<div class="actis">
<%= button_to "OUT", destroy_user_session_path, method: :delete, class: "btnn" %>
</div>
</div>
<% total = 0 %>
<% @category.items.each do |item| %>
  <% total += item.amount %>
<% end %>

<div class="flex-bold2">
  <p>Gift Credit</p>
  <p>$<%= total %></p>
</div>

<div>
        <% @category.items.each do |item| %>
        <div class="flex-bold">
        <div class="flex-bold1">
            <p><%= item.name %></p>
            <p>$<%= item.amount %></p>
        </div>
            <p><%= item.created_at.strftime('%d-%b-%Y') %> <p>
        </div>
        <% end %>
</div>


<div class="new-cs">
<p class="new-s"><%= link_to 'New Category Item', new_category_item_path(@category.id) %></p>
</div>

</div>

app/views/items/new.html.erb
<%= form_with model: @item, url: category_items_path,  method: :post do | form | %>
  <div class="back-lin">
  <%= link_to categories_path(@category) do %>
    <%= image_tag('icons8-left-24 (1).png') %>
  <% end %>
  <h2>NEW CATEGORY</h2>
  <div class="acti">
  <%= form.submit "Save", class: "btnn" %>
  </div>
  </div>
  <% if @item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.text_field :amount %>
  </div>
<div>
  <p> Choose One or More Balance Sheets to Add This Item</p>
  <div class="choos">
   <% @categories.each do |category| %>
              <% checked = category.id.to_i == params[:category_id].to_i ? { checked: true } : {} %>
              <div class="flex-choos">
                  <%= form.check_box :selected_ids, { multiple: true}.merge(checked), category.id, nil%>
                  
                  <%= label_tag "category_#{category.id}", category.name %>
              </div>
    <% end %>
     </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTrackr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<!-- app/views/splash/index.html.erb -->
<ul class="nav-items">
<% if user_signed_in? %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn' %>

<% else %>
<div class="splash">
<div class="nam">
  <h1>BudgetTrack</h1>
</div>
<div class="login-links">
  <%= link_to 'LOG IN', new_user_session_path, class: 'btn-a' %>
  <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn' %>
</div>
</div>
<% end %>